// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/28 18:11:39
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/33024/claude-code-myblogs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/plugins/**/*.{js,ts,mjs}","F:/33024/claude-code-myblogs/composables/**/*.{js,ts,mjs}","F:/33024/claude-code-myblogs/utils/**/*.{js,ts,mjs}","F:/33024/claude-code-myblogs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/33024/claude-code-myblogs/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["23"] = "F:/33024/claude-code-myblogs/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;